// Filesystem CLI: no pg import, credential environment or live mode. Callers
// must supply trusted private local paths; this is not filesystem confinement.
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createSnapshot, verifySnapshot, restoreFile, parseJson, readPrivateFile, writeNewFile, fault } from "./lib/recovery.mjs";

const USAGE = `Local Hearth recovery (Node 24):
  keygen --out <new-key-file>
  create --source <private-world.json> --key-file <archive-key> --out <new-archive>
  verify --archive <archive> --key-file <archive-key> --expect <trusted-archive-sha256>
  restore --archive <archive> --key-file <archive-key> --expect <trusted-archive-sha256> --out <new-world.json>
All output paths must be new. No overwrite, database connection or automatic cutover.
Use a private local directory. A restored world can contain legacy plaintext.
Keep the archive key and trusted digest separately from the encrypted archive.
`;
export async function main(args, output = line => console.log(line)) {
  let key;
  try {
    if (args.length === 1 && ["--help", "help"].includes(args[0])) { output(USAGE); return 0; }
    const [command, ...flags] = args;
    const allowed = {
      keygen: ["out"], create: ["source","key-file","out"],
      verify: ["archive","key-file","expect"], restore: ["archive","key-file","expect","out"],
    }[command];
    if (!allowed || flags.length !== allowed.length * 2) throw fault("usage");
    const options = Object.create(null);
    for (let i = 0; i < flags.length; i += 2) {
      const name = flags[i].slice(2), value = flags[i + 1];
      if (!flags[i].startsWith("--") || !allowed.includes(name) || Object.hasOwn(options, name) || !value || value.startsWith("--")) throw fault("usage");
      options[name] = value;
    }
    if (command === "keygen") {
      key = randomBytes(32); await writeNewFile(options.out, key);
      output(JSON.stringify({ ok: true, action: "created_archive_key", bytes: 32 })); return 0;
    }
    key = await readPrivateFile(options["key-file"], 32);
    if (key.length !== 32) throw fault("invalid_archive_key");
    let receipt;
    if (command === "create") {
      const world = parseJson(await readPrivateFile(options.source));
      const snapshot = createSnapshot(world, key);
      // Verify generated bytes before creating an artifact, not just on restore.
      verifySnapshot(snapshot.bytes, key, snapshot.receipt.archive_sha256);
      await writeNewFile(options.out, snapshot.bytes); receipt = snapshot.receipt;
    } else {
      const bytes = await readPrivateFile(options.archive);
      receipt = command === "restore"
        ? await restoreFile(bytes, key, options.expect, options.out)
        : verifySnapshot(bytes, key, options.expect).receipt;
    }
    output(JSON.stringify(receipt)); return 0;
  } catch (err) {
    // Error codes are generated here, never raw backend/file/parser messages.
    const codes = new Set(["usage","invalid_snapshot","size_limit","invalid_json","invalid_archive_key","incompatible_snapshot",
      "expected_digest_required","archive_digest_mismatch","state_digest_mismatch","archive_authentication_failed",
      "unsafe_file","source_changed","file_read_failed","destination_exists","output_incomplete","output_verification_failed"]);
    output(JSON.stringify({ ok: false, error_class: codes.has(err?.code) ? err.code : "recovery_failed" })); return 1;
  } finally { key?.fill(0); }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exitCode = await main(process.argv.slice(2));
